views:
  - title: Layout Testcase
    panel: true
    cards:
      - type: 'custom:cards-layout'
        title: Auswertung (Header)
        icon: 'mdi:tape-measure'
        description: |
          Testanzeige für verschiedene Darstellungungen:
          <ul>
            <li>Bilder</>
            <li>Grafiken</>
            <li>Buttons</>
          </ul>
        width: 80%
        rows:
          - row:
              - col: null
                width: 100%
                title: Testcase Picture
                description: Darstellung mit einer picture-glance card.
                entities:
                  - type: picture-glance
                    title: Eingang
                    image: /local/images/rooms/eingang.jpg
                    entities:
                      - entity: sensor.orangenbaum_battery
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                      - entity: sensor.gas_verbrauch_m3
                      - entity: sensor.temperatur_indoo
          - row:
              - col: null
                width: 50%
                height: 320
                title: Testcase mit lovelace cards
                description: >-
                  Darstellung der Karten custom:simple-card, lovelace-markdown,
                  custom:chart-card, custom:mini-graph-card.
                entities:
                  - type: 'custom:simple-card'
                    clock: true
                    style: >
                      height:300px; background: rgba(0, 0, 0, 0)
                      linear-gradient(rgb(241, 39,17), rgb(245, 175, 25)) repeat
                      scroll 0% 0%; height: 300px; color: #FFFFFF
                    title: Willkommen Fremder
                    icon: 'mdi:home'
                    text: >-
                      Dies ist ein Beispiel für eine einfache Karte mit einer
                      Uhr.
                    entities:
                      - sun.sun
                  - type: markdown
                    style: >
                      height:300px; background: linear-gradient(45deg, #5fc9f8,
                      #fecb2e, #fd9426, #fc3158, #147efb, #53d769);
                    content: |
                      Hello, {{user}} 
                      markdown card sample
                  - type: 'custom:chart-card'
                    title: Makro Nährstoffe
                    icon: 'mdi:chart-pie'
                    height: 240
                    chart: pie
                    units: kal
                    cardtimestamp: true
                    theme:
                      cardbackground: |
                        linear-gradient(to bottom, #40e0d0, #ff8c00, #ff0080);
                    options:
                      plugins:
                        title:
                          display: true
                          text: Aufteilung Nährstoffe (kal) pro Tag
                          color: '#ff9500'
                    entities:
                      - entity: sensor.eiweis_makronahrstoff
                        name: Eiweis
                      - entity: sensor.fett_makronahrstoff
                        name: Fett
                      - entity: sensor.kohlenhydrate_makronahrstoff
                        name: Kohlenhydrate
                  - type: 'custom:chart-card'
                    title: Makro Nährstoffe
                    icon: 'mdi:chart-bar'
                    height: 240
                    chart: bar
                    units: kal
                    cardtimestamp: true
                    theme:
                      cardbackground: |
                        linear-gradient(to bottom, #e1eec3,#f05053);
                    show:
                      segmented: true
                    options:
                      plugins:
                        title:
                          display: true
                          text: Aufteilung Nährstoffe (kal) pro Tag
                        legend:
                          display: false
                    entities:
                      - entity: sensor.eiweis_makronahrstoff
                        name: Eiweis
                        backgroundColor: '#f1c40f'
                        units: kal
                      - entity: sensor.fett_makronahrstoff
                        name: Fett
                        backgroundColor: '#e74c3c'
                        units: kal
                      - entity: sensor.kohlenhydrate_makronahrstoff
                        name: Kohlenhydrate
                        backgroundColor: '#009688'
                        units: kal
                  - type: 'custom:chart-card'
                    title: Makro Nährstoffe
                    icon: 'mdi:radar'
                    height: 240
                    chart: radar
                    units: kal
                    cardtimestamp: true
                    theme:
                      cardbackground: |
                        linear-gradient(to bottom, #e1eec3,#f05053);
                    options:
                      scale:
                        gridLines:
                          color:
                            - '#03a9f4'
                            - '#00bcd4'
                            - '#8bc34a'
                            - '#e51400'
                            - '#cddc39'
                            - '#ff9800'
                            - '#ff5722'
                        angleLines:
                          color: '#5ac8fa'
                    entities:
                      - entity: sensor.eiweis_makronahrstoff
                        name: Eiweis
                        units: kal
                      - entity: sensor.fett_makronahrstoff
                        name: Fett
                        units: kal
                      - entity: sensor.kohlenhydrate_makronahrstoff
                        name: Kohlenhydrate
                        units: kal
                  - type: 'custom:chart-card'
                    title: Körperwerte
                    icon: 'mdi:poll-box-outline'
                    height: 240
                    chart: polarArea
                    cardtimestamp: true
                    options:
                      plugins:
                        title:
                          text: Aktuelle Werte
                      scale:
                        gridLines:
                          color:
                            - '#03a9f4'
                            - '#00bcd4'
                            - '#8bc34a'
                            - '#e51400'
                            - '#cddc39'
                            - '#ff9800'
                            - '#ff5722'
                        angleLines:
                          color: '#5ac8fa'
                    entities:
                      - entity: sensor.koperfett
                        name: Fett
                      - entity: sensor.korperwasser
                        name: Wasser
                      - entity: sensor.muskeln
                        name: Muskeln
                      - entity: sensor.fettfreie_korpermasse
                        name: Fettfreie Masse
                      - entity: sensor.gewicht
                        name: Gewicht
                      - entity: sensor.viszerales_fett
                        name: Viszerales Fett
                  - type: 'custom:chart-card'
                    title: 'LINE custom:chart-card'
                    icon: 'mdi:chart-line'
                    height: 240
                    chart: line
                    cardtimestamp: true
                    ignoreZero: true
                    theme:
                      cardbackground: |
                        linear-gradient(to bottom, #40e0d0, #ff8c00,#ff0080);
                    options:
                      plugins:
                        title:
                          display: true
                          text: Gasverbrauch
                      layout:
                        padding:
                          left: 50
                          right: 50
                          top: 0
                          bottom: 0
                    entities:
                      - entity: sensor.gas_verbrauch_m3
                  - type: 'custom:chart-card'
                    title: 'LINE2 custom:chart-card'
                    icon: 'mdi:chart-bell-curve-cumulative'
                    height: 240
                    chart: line
                    loader: three-dots
                    cardtimestamp: true
                    theme:
                      cardbackground: |
                        linear-gradient(to bottom, #e1eec3, #f05053)
                    options:
                      plugins:
                        title:
                          display: true
                          text: Innnenraum
                        legend:
                          display: false
                      layout:
                        padding:
                          left: 50
                          right: 50
                          top: 0
                          bottom: 0
                    entities:
                      - entity: sensor.temperatur_indoor
                        fill: true
                  - type: 'custom:mini-graph-card'
                    style: >
                      background: linear-gradient(to top, #fc4a1a, #f7b733);
                      color:#FFFFFF
                    entities:
                      - entity: sensor.temperatur_indoor
                        name: Innenraum
                      - entity: sensor.orangenbaum_light
                        name: Licht
                        y_axis: secondary
          - row:
              - col: null
                width: 240
                height: 240
                entities:
                  - type: sensor
                    graph: line
                    entity: sensor.temperatur_indoor
                    name: lovelace sensor
                  - type: sensor
                    graph: line
                    name: Orangenbaum
                    entity: sensor.orangenbaum_temperature
          - row:
              - col: null
                width: 320
                height: 420
                entities:
                  - type: light
                    entity: light.fitnessraum_licht
                    style: |
                      overflow:hidden;
                      transform: scale(98%);
                  - type: thermostat
                    entity: climate.zentralheizung
                    style: |
                      overflow:hidden;
                      transform: scale(98%);
                  - type: alarm-panel
                    name: House Alarm
                    entity: alarm_control_panel.home_alarm
                    style: |
                      overflow:hidden;
                      transform: scale(95%);
                  - type: 'custom:simple-card'
                    title: Wetterdaten
                    icon: 'mdi:weather-cloudy'
                    mode: entities_card
                    filter:
                      include:
                        - key: weather.home.temperature
                          name: Temperatur
                          icon: 'mdi:thermometer'
                          unit: °C
                        - key: weather.home.humidity
                          name: Feuchtigkeit
                          icon: 'mdi:water'
                          unit: '%'
                  - type: 'custom:simple-card'
                    title: Wetterdaten
                    height: 360
                    icon: 'mdi:weather-cloudy'
                    mode: entities_card
                    filter:
                      include:
                        - weather.home.*
          - row:
              - col: null
                entities:
                  - type: 'custom:simple-card'
                    title: Anzeige von Buttons mit Status
                    icon: 'mdi:home'
                    mode: buttons
                    entities:
                      - entity: person.admin
                        name: Peter
                        image: /local/images/peter.jpg
                      - entity: person.admin
                        name: Peter
                        photo: /local/images/peter.jpg  
                      - entity: sensor.gas_verbrauch_m3
                        name: Gas
                      - entity: sensor.kohlenhydrate_makronahrstoff
                        name: Kohlenhydrate
                      - entity: sensor.hacs
                        style: >
                          background: linear-gradient(to bottom, #ffc500,
                          #c21500);color: #FFFFFF;
                      - entity: sensor.temperatur_indoor
                        type: digitbutton
                      - entity: sensor.orangenbaum_light
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                        type: digitbutton
                      - entity: binary_sensor.night
                      - entity: binary_sensor.updater
                      - entity: sensor.gasuhr_status
                      - entity: sun.sun
                      - entity: weather.home
                      - entity: light.fitnessraum_licht
                        icon: 'mdi:floor-lamp'
                      - entity: climate.zentralheizung
                      - entity: alarm_control_panel.home_alarm
