views:
  - title: Layout Testcase
    panel: true
    cards:
      - type: 'custom:cards-layout'
        title: Auswertung (Header)
        icon: 'mdi:tape-measure'
        description: |
          Testanzeige für verschiedene Darstellungungen:
          <ul>
            <li>Bilder</>
            <li>Grafiken</>
            <li>Buttons</>
          </ul>
        width: 80%
        cards:
          - row:
              - col: null
                width: 100%
                title: Testcase Picture
                description: Darstellung mit einer picture-glance card.
                entities:
                  - type: picture-glance
                    title: Eingang
                    image: /local/images/rooms/eingang.jpg
                    entities:
                      - entity: sensor.orangenbaum_battery
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                      - entity: sensor.gas_verbrauch_m3
                      - entity: sensor.temperatur_indoor
          - row:
              - col: null
                width: 50%
                height: 320
                title: Testcase mit lovelace cards
                description: >-
                  Darstellung der Karten custom:simple-card, lovelace-markdown,
                  custom:chart-card, custom:mini-graph-card.
                entities:
                  - type: 'custom:simple-card'
                    clock: true
                    style: >
                      height:300px; background: rgba(0, 0, 0, 0)
                      linear-gradient(rgb(241, 39,17), rgb(245, 175, 25)) repeat
                      scroll 0% 0%; height: 300px; color: #FFFFFF
                    title: Willkommen Fremder
                    icon: 'mdi:home'
                    text: >-
                      Dies ist ein Beispiel für eine einfache Karte mit einer
                      Uhr.
                    entities:
                      - sun.sun
                  - type: markdown
                    style: >
                      height:300px; background: linear-gradient(45deg, #5fc9f8,
                      #fecb2e, #fd9426, #fc3158, #147efb, #53d769);
                    content: |
                      Hello, {{user}} 
                      markdown card sample
                  - type: 'custom:chart-card'
                    title: 'PIE - custom:chart-card'
                    icon: 'mdi:nutrition'
                    height: 220
                    maxwidth: 420
                    chart: pie
                    theme:
                      cardbackground: 'linear-gradient(to bottom, #e6dada, #274046);'
                    options:
                      title:
                        display: true
                        text: Orangenbaum
                    entities:
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                  - type: 'custom:chart-card'
                    style: |
                      background: linear-gradient(to bottom, #009fff, #ec2f4b);
                    title: 'BAR - custom:chart-card'
                    icon: 'mdi:nutrition'
                    height: 220
                    maxwidth: 420
                    chart: bar
                    options:
                      title:
                        display: true
                        text: Orangenbaum
                    entities:
                      - entity: sensor.orangenbaum_battery
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                  - type: 'custom:chart-card'
                    style: |
                      background: linear-gradient(to bottom, #009fff, #ec2f4b);
                    title: 'LINE custom:chart-card'
                    icon: 'mdi:nutrition'
                    height: 220
                    maxwidth: 420
                    chart: line
                    options:
                      title:
                        display: true
                        text: Gasverbrauch
                      layout:
                        padding:
                          left: 50
                          right: 50
                          top: 0
                          bottom: 0
                    entities:
                      - entity: sensor.gas_verbrauch_m3
                  - type: 'custom:chart-card'
                    title: 'LINE2 custom:chart-card'
                    icon: 'mdi:chart-box'
                    height: 220
                    maxwidth: 420
                    chart: line
                    loader: three-dots
                    options:
                      title:
                        display: true
                        text: Innnenraum
                      layout:
                        padding:
                          left: 50
                          right: 50
                          top: 0
                          bottom: 0
                    entities:
                      - entity: sensor.temperatur_indoor
                        fill: true
                  - type: 'custom:mini-graph-card'
                    style: >
                      background: linear-gradient(to top, #fc4a1a, #f7b733);
                      color:#FFFFFF
                    entities:
                      - entity: sensor.temperatur_indoor
                        name: Innenraum
                      - entity: sensor.orangenbaum_light
                        name: Licht
                        y_axis: secondary
          - row:
              - col: null
                width: 160
                height: 160
                entities:
                  - type: sensor
                    graph: line
                    entity: sensor.temperatur_indoor
                    name: lovelace sensor
                  - type: sensor
                    graph: line
                    name: Orangenbaum
                    entity: sensor.orangenbaum_temperature
          - row:
              - col: null
                width: 280
                height: 240
                entities:
                  - type: light
                    entity: light.fitnessraum_licht
                  - type: thermostat
                    entity: climate.zentralheizung
                    style: |
                      max-height: 240px
                  - type: alarm-panel
                    name: House Alarm
                    entity: alarm_control_panel.home_alarm
                    style: |
                      max-height: 240px;
                      overflow:hidden;
                  - type: 'custom:simple-card'
                    title: Wetterdaten
                    icon: 'mdi:weather-cloudy'
                    mode: entities_card
                    entity: weather.home
                    filter:
                      include:
                        - key: weather.home.temperature
                          name: Temperatur
                          icon: 'mdi:thermometer'
                          unit: °C
                        - key: weather.home.humidity
                          name: Feuchtigkeit
                          icon: 'mdi:water'
                          unit: '%'
          - row:
              - col: null
                entities:
                  - type: 'custom:simple-card'
                    title: Anzeige von Buttons mit Status
                    icon: 'mdi:home'
                    mode: buttons
                    entities:
                      - entity: person.admin
                        name: Peter
                        image: /local/images/peter.jpg
                      - entity: sensor.gas_verbrauch_m3
                        name: Gas
                      - entity: sensor.kohlenhydrate_makronahrstoff
                        name: Kohlenhydrate
                      - entity: sensor.hacs
                        style: >
                          background: linear-gradient(to bottom, #ffc500,
                          #c21500);color: #FFFFFF;
                      - entity: sensor.temperatur_indoor
                        type: digitbutton
                      - entity: sensor.orangenbaum_light
                      - entity: sensor.orangenbaum_moisture
                      - entity: sensor.orangenbaum_temperature
                      - entity: sensor.orangenbaum_conductivity
                        type: digitbutton
                      - entity: binary_sensor.night
                      - entity: binary_sensor.updater
                      - entity: sensor.gasuhr_status
                      - entity: sun.sun
                      - entity: weather.home
                      - entity: light.fitnessraum_licht
                        icon: 'mdi:floor-lamp'
                      - entity: climate.zentralheizung
                      - entity: alarm_control_panel.home_alarm
